version: "1"
services:
  apigateway:
    container_name: apigateway
    restart: always
    image: agalend/pay-smartly-apigateway-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9080
      - UI_ENDPOINTS=["http://ui1:9081/","http://ui2:9082/"]
      - CALCULATIONS_ENDPOINTS=["http://calculations1:9083/","http://calculations2:9084/"]
      - ARCHIVE_ENDPOINTS=["http://archive1:9085/", "http://archive2:9086/"]
    ports:
      - "9080:9080"
    links:
      - ui1
      - ui2
      - calculations1
      - calculations2
      - archive1
      - archive2
  ui1:
    container_name: ui1
    restart: always
    image: agalend/pay-smartly-ui-service
    environment:
      - NODE_ENV=production
      - PORT=9081
    ports:
      - "9081:9081"
  ui2:
    container_name: ui2
    restart: always
    image: agalend/pay-smartly-ui-service
    environment:
      - NODE_ENV=production
      - PORT=9082
    ports:
      - "9082:9082"
  calculations1:
    container_name: calculations1
    restart: always
    image: agalend/pay-smartly-calculations-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9083
      - PERSISTANCE_URL=http://persistancelb:9087
      - LEGISLATION_URL=http://legislation:9090
    ports:
      - "9083:9083"
    links:
      - persistancelb
      - legislation
  calculations2:
    container_name: calculations2
    restart: always
    image: agalend/pay-smartly-calculations-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9084
      - PERSISTANCE_URL=http://persistancelb:9087
      - LEGISLATION_URL=http://legislation:9090
    ports:
      - "9084:9084"
    links:
      - persistancelb
      - legislation
  archive1:
    container_name: archive1
    restart: always
    image: agalend/pay-smartly-archive-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9085
      - PERSISTANCE_URL=http://persistancelb:9087
    ports:
      - "9085:9085"
    links:
      - persistancelb
  archive2:
    container_name: archive2
    restart: always
    image: agalend/pay-smartly-archive-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9086
      - PERSISTANCE_URL=http://persistancelb:9087
    ports:
      - "9086:9086"
    links:
      - persistancelb
  legislation:
    container_name: legislation
    restart: always
    image: agalend/pay-smartly-legislation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9090
    ports:
      - "9090:9090"
  persistancelb:
    container_name: persistancelb
    restart: always
    image: agalend/pay-smartly-loadbalancer-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KESTREL_ENDPOINT_PORT=9087
      - PERSISTANCE_ENDPOINTS=["http://persistance1:9088/","http://persistance2:9089/"]
    ports:
      - "9087:9087"
    links:
      - persistance1
      - persistance2
  persistance1:
    container_name: persistance1
    restart: always
    image: agalend/pay-smartly-persistance-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9088
      - CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "9088:9088"
    links:
      - mongo
  persistance2:
    container_name: persistance2
    restart: always
    image: agalend/pay-smartly-persistance-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9089
      - CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "9089:9089"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      #- ${WEBAPP_STORAGE_HOME}/site:/data/db
      - ./data:/data/db
    ports:
      - "27017:27017"